/** Every value the presentational tree reads. Produced by ShellController.renderVals(). */
export interface ShellVals {
  activeLabel: string;
  connect: (...args: any[]) => void;
  disconnect: (...args: any[]) => void;
  isConnected: boolean;
  isDisconnected: boolean;
  navItems: any[];
  onCurrency: (...args: any[]) => void;
  onRefresh: (...args: any[]) => void;
  onVaultView: (...args: any[]) => void;
  p3AccChevron: string;
  p3AccOpen: boolean;
  p3AccToggle: (...args: any[]) => void;
  p3Assets: any[];
  p3Dd: string;
  p3Pos: string;
  p3PosActive: boolean;
  p3PosNone: boolean;
  p3PosStatus: string;
  p3PosStatusColor: string;
  p3Share: string;
  p3Trades: string;
  p4AccChevron: string;
  p4AccOpen: boolean;
  p4AccToggle: (...args: any[]) => void;
  p4Assets: any[];
  p4Dd: string;
  p4Pos: string;
  p4PosActive: boolean;
  p4PosNone: boolean;
  p4PosStatus: string;
  p4PosStatusColor: string;
  p4Share: string;
  p4Trades: string;
  p5AccChevron: string;
  p5AccOpen: boolean;
  p5AccToggle: (...args: any[]) => void;
  p5Assets: any[];
  p5Dd: string;
  p5Pos: string;
  p5PosStatus: string;
  p5PosStatusColor: string;
  p5RealBtcW: string;
  p5RealSplit: string;
  p5RealUsdcW: string;
  p5Share: string;
  p5Trades: string;
  pageDesc: string;
  pageTitle: string;
  pfAlloc: any[];
  pfFeed: any[];
  pfLoading: boolean;
  pfLocked: boolean;
  pfReady: boolean;
  pfSegments: any[];
  pfTotal: string;
  pfWallet: string;
  pvDecisions: any[];
  pvFilters: any[];
  setCurrency: string;
  setRefresh: string;
  setVaultView: string;
  strategiesDisplay: string;
  tlDecisions: any[];
  tlEmpty: boolean;
  tlFilters: any[];
  tvlDisplay: string;
  v3ActivePill: boolean;
  v3Allowance: string;
  v3Amount: string;
  v3Capacity: string;
  v3ChevRot: string;
  v3CtaBg: string;
  v3CtaColor: string;
  v3CtaCursor: string;
  v3CtaDisabled: boolean;
  v3CtaHoverBg: string;
  v3CtaLabel: string;
  v3CtaOpacity: string;
  v3DepBg: string;
  v3DepColor: string;
  v3Err: string;
  v3FormReady: boolean;
  v3HasErr: boolean;
  v3InBorder: string;
  v3InDisabled: boolean;
  v3InOpacity: string;
  v3IsDep: boolean;
  v3LimitClick: (...args: any[]) => void;
  v3Limited: boolean;
  v3Loaded: boolean;
  v3Loading: boolean;
  v3Locked: boolean;
  v3LpActive: boolean;
  v3LpNone: boolean;
  v3MetaLabel: string;
  v3MetaValue: string;
  v3MyPos: string;
  v3OnAmount: (...args: any[]) => void;
  v3Open: boolean;
  v3PosVal: string;
  v3Rows: string;
  v3SelDep: (...args: any[]) => void;
  v3SelWd: (...args: any[]) => void;
  v3SetMax: (...args: any[]) => void;
  v3ShowLimit: boolean;
  v3Submit: (...args: any[]) => void;
  v3Timeline: any[];
  v3TlChevron: string;
  v3TlOpen: boolean;
  v3TlToggle: (...args: any[]) => void;
  v3Toggle: (...args: any[]) => void;
  v3Tvl: string;
  v3TxCancel: boolean;
  v3TxFail: boolean;
  v3TxOk: boolean;
  v3TxUrl: string;
  v3UserLoading: boolean;
  v3WdBg: string;
  v3WdColor: string;
  v3YieldVal: string;
  v4ActivePill: boolean;
  v4Allowance: string;
  v4Amount: string;
  v4Apy: string;
  v4Capacity: string;
  v4ChevRot: string;
  v4CtaBg: string;
  v4CtaColor: string;
  v4CtaCursor: string;
  v4CtaDisabled: boolean;
  v4CtaHoverBg: string;
  v4CtaLabel: string;
  v4CtaOpacity: string;
  v4DepBg: string;
  v4DepColor: string;
  v4Err: string;
  v4FormReady: boolean;
  v4HasErr: boolean;
  v4HasPos: boolean;
  v4InBorder: string;
  v4InDisabled: boolean;
  v4InOpacity: string;
  v4IsDep: boolean;
  v4Limited: boolean;
  v4Loaded: boolean;
  v4Loading: boolean;
  v4Locked: boolean;
  v4MetaLabel: string;
  v4MetaValue: string;
  v4MyPos: string;
  v4NoPos: boolean;
  v4OnAmount: (...args: any[]) => void;
  v4Open: boolean;
  v4PosVal: string;
  v4Rows: string;
  v4SelDep: (...args: any[]) => void;
  v4SelWd: (...args: any[]) => void;
  v4SetMax: (...args: any[]) => void;
  v4StageLabel: string;
  v4Steps: any[];
  v4Submit: (...args: any[]) => void;
  v4Timeline: any[];
  v4TlChevron: string;
  v4TlOpen: boolean;
  v4TlToggle: (...args: any[]) => void;
  v4Toggle: (...args: any[]) => void;
  v4Tvl: string;
  v4TxCancel: boolean;
  v4TxFail: boolean;
  v4TxOk: boolean;
  v4TxUrl: string;
  v4UserLoading: boolean;
  v4WdBg: string;
  v4WdColor: string;
  v4YieldVal: string;
  v5ActivePill: boolean;
  v5Allowance: string;
  v5Amount: string;
  v5BtcLabel: string;
  v5BtcPct: string;
  v5Capacity: string;
  v5ChevRot: string;
  v5CtaBg: string;
  v5CtaColor: string;
  v5CtaCursor: string;
  v5CtaDisabled: boolean;
  v5CtaHoverBg: string;
  v5CtaLabel: string;
  v5CtaOpacity: string;
  v5DepBg: string;
  v5DepColor: string;
  v5Err: string;
  v5FormReady: boolean;
  v5GoPaper: (...args: any[]) => void;
  v5HasErr: boolean;
  v5InBorder: string;
  v5InDisabled: boolean;
  v5InOpacity: string;
  v5IsDep: boolean;
  v5LimitClick: (...args: any[]) => void;
  v5Limited: boolean;
  v5Loaded: boolean;
  v5Loading: boolean;
  v5Locked: boolean;
  v5MetaLabel: string;
  v5MetaValue: string;
  v5MyPos: string;
  v5OnAmount: (...args: any[]) => void;
  v5Open: boolean;
  v5PosVal: string;
  v5Rows: string;
  v5SelDep: (...args: any[]) => void;
  v5SelWd: (...args: any[]) => void;
  v5SetMax: (...args: any[]) => void;
  v5ShowLimit: boolean;
  v5Submit: (...args: any[]) => void;
  v5Timeline: any[];
  v5TlChevron: string;
  v5TlOpen: boolean;
  v5TlToggle: (...args: any[]) => void;
  v5Toggle: (...args: any[]) => void;
  v5Tvl: string;
  v5TxCancel: boolean;
  v5TxFail: boolean;
  v5TxOk: boolean;
  v5TxUrl: string;
  v5UsdcLabel: string;
  v5UsdcPct: string;
  v5UserLoading: boolean;
  v5WdBg: string;
  v5WdColor: string;
  v5YieldVal: string;
  v7ActivePill: boolean;
  v7Allowance: string;
  v7Amount: string;
  v7Capacity: string;
  v7ChevRot: string;
  v7CtaBg: string;
  v7CtaColor: string;
  v7CtaCursor: string;
  v7CtaDisabled: boolean;
  v7CtaHoverBg: string;
  v7CtaLabel: string;
  v7CtaOpacity: string;
  v7DepBg: string;
  v7DepColor: string;
  v7Err: string;
  v7FormReady: boolean;
  v7HasErr: boolean;
  v7InBorder: string;
  v7InDisabled: boolean;
  v7InOpacity: string;
  v7IsDep: boolean;
  v7Limited: boolean;
  v7Loaded: boolean;
  v7Loading: boolean;
  v7Locked: boolean;
  v7LpActive: boolean;
  v7LpLower: string;
  v7LpNone: boolean;
  v7LpPrice: string;
  v7LpPriceLeft: string;
  v7LpRangeLeft: string;
  v7LpRangeWidth: string;
  v7LpUpper: string;
  v7LpValue: string;
  v7MetaLabel: string;
  v7MetaValue: string;
  v7MyPos: string;
  v7OnAmount: (...args: any[]) => void;
  v7Open: boolean;
  v7PosVal: string;
  v7Rows: string;
  v7SelDep: (...args: any[]) => void;
  v7SelWd: (...args: any[]) => void;
  v7SetMax: (...args: any[]) => void;
  v7Submit: (...args: any[]) => void;
  v7Timeline: any[];
  v7TlChevron: string;
  v7TlOpen: boolean;
  v7TlToggle: (...args: any[]) => void;
  v7Toggle: (...args: any[]) => void;
  v7Tvl: string;
  v7TxCancel: boolean;
  v7TxFail: boolean;
  v7TxOk: boolean;
  v7TxUrl: string;
  v7UserLoading: boolean;
  v7WdBg: string;
  v7WdColor: string;
  v7YieldVal: string;
  walletDisplay: string;
  wlAddress: string;
  wlAmount: string;
  wlAmtBorder: string;
  wlAmtErr: string;
  wlAssetCount: string;
  wlAssets: any[];
  wlBack: (...args: any[]) => void;
  wlBalance: string;
  wlCloseRcv: (...args: any[]) => void;
  wlConfirm: (...args: any[]) => void;
  wlCopy: (...args: any[]) => void;
  wlCopyLabel: string;
  wlFeed: any[];
  wlHasAmtErr: boolean;
  wlHasToErr: boolean;
  wlLoading: boolean;
  wlLocked: boolean;
  wlMax: (...args: any[]) => void;
  wlOnAmount: (...args: any[]) => void;
  wlOnTo: (...args: any[]) => void;
  wlOnToken: (...args: any[]) => void;
  wlOpenRcv: (...args: any[]) => void;
  wlQrHtml: string;
  wlRcvOpen: boolean;
  wlReady: boolean;
  wlReset: (...args: any[]) => void;
  wlRevAmt: string;
  wlRevCtaBg: string;
  wlRevCtaColor: string;
  wlRevCtaCursor: string;
  wlRevCtaHoverBg: string;
  wlRevTo: string;
  wlRevToShort: string;
  wlRevTotal: string;
  wlReview: (...args: any[]) => void;
  wlReviewDisabled: boolean;
  wlSendCardBg: string;
  wlSendCardBorder: string;
  wlSendOpen: boolean;
  wlSentAmt: string;
  wlSentTo: string;
  wlShare: (...args: any[]) => void;
  wlStepCancelled: boolean;
  wlStepFailed: boolean;
  wlStepForm: boolean;
  wlStepPending: boolean;
  wlStepReview: boolean;
  wlStepSuccess: boolean;
  wlStop: (...args: any[]) => void;
  wlTo: string;
  wlToBorder: string;
  wlToErr: string;
  wlToggleSend: (...args: any[]) => void;
  wlToken: string;
  wlTotal: string;
  wlTxUrl: string;
  [key: string]: any;
}

/** Configurable inputs to the shell (were design-time tweaks). */
export interface ShellProps {
  walletDisplay?: string;
  scenario?: 'today' | 'live demo';
  v4Stage?: 'in transit' | 'open' | 'withdrawal pending' | 'returning';
  txOutcome?: 'success' | 'cancelled' | 'failed';
  // Real Privy auth state, Phase 1 wiring (see ShellControllerWithAuth in
  // ShellController.tsx). undefined only in the brief instant before
  // Privy's own `ready` flag resolves.
  privyReady?: boolean;
  authenticated?: boolean;
  userAddress?: `0x${string}`;
  onLogin?: () => void;
  onLogout?: () => void;
  onCreateWallet?: () => Promise<void>;
}

export const defaultShellProps: ShellProps = {
  walletDisplay: "0x7f3A…9c4E",
  scenario: "today",
  v4Stage: "open",
  txOutcome: "success",
};
